services:
  - type: web
    name: print3d-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python web/api.py
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
